name: entity-core

networks:
  shared-net:
    external: true

services:
  entity-core-postgres:
    image: postgres:16
    container_name: entity-core-postgres
    tmpfs:
      - /var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    ports:
      - "127.0.0.1:5432:5432"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "PGPASSWORD=\"$${POSTGRES_PASSWORD}\" pg_isready -h 127.0.0.1 -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - shared-net

  bootstrap:
    build:
      context: ..
      dockerfile: deploy/docker/bootstrap/Dockerfile
    image: entity-core-api/bootstrap:local
    env_file:
      - ./env/postgres.env
    depends_on:
      entity-core-postgres:
        condition: service_healthy
    command:
      - bash
      - -lc
      - |
        /scripts/bootstrap.sh
        /scripts/init-postgres.sh
    restart: no
    networks:
      - shared-net

  entity-core-api:
    build:
      context: ..
      dockerfile: deploy/docker/entity-core-api/Dockerfile
    image: entity-core-api:local
    env_file:
      - ./env/entity-core-api.env
      - ./env/postgres.env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8004:8004"
    networks:
      - shared-net

  entity-core:
    build:
      context: ..
      dockerfile: deploy/docker/entity-core/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "https://entity-core.fullstackjedi.dev/api"
        NEXT_PUBLIC_AUTH0_DOMAIN: "dev-gttnobig6h3trkvm.us.auth0.com"
        NEXT_PUBLIC_AUTH0_CLIENT_ID: "9J5htp4HKGaUV58ZX9E8FQ2ldot7SnkO"
        NEXT_PUBLIC_AUTH0_AUDIENCE: "https://entity-core.fullstackjedi.dev/api"
        NEXT_PUBLIC_AUTH0_NAMESPACE: "https://fullstackjedi.dev"
        NEXT_PUBLIC_AUTH0_SCOPE: "openid profile email crud:read crud:create crud:update crud:delete offline_access"
        NEXT_PUBLIC_AUTH0_REDIRECT_URI: "https://entity-core.fullstackjedi.dev/callback"
        NEXT_PUBLIC_DISABLE_AUTH: "false"
    image: entity-core:local
    env_file:
      - ./env/entity-core.env

    restart: unless-stopped
    ports:
      - "127.0.0.1:3006:3006"
    networks:
      - shared-net